### ISSUE TITLE
Resolve plugins from Ivy Repositories

### ISSUE THREAD

**Issue by eljobe** [gradle/stable-plugins-dsl#12]
We have added the concept of a POM-only marker artifact to the Maven repositories to provide a stable mapping from a `pluginid` and `version` to the artifact that actually contains the plugin.  We need to introduce a similar concept for Ivy repositories and confirm that we can resolve plugin artifacts from those as well.

**Comment by oehme** [comment]
The code and test coverage look good and I successfully tested it manually in our example project 👍
