### ISSUE TITLE
Can parse Plugin Repository declarations in settings.gradle

### ISSUE THREAD

**Issue by oehme** [gradle/stable-plugins-dsl#17]
## Motivation

To allow users to specify their custom repositories, Gradle first of all needs to be able to parse the new `pluginRepositories` DSL.

## Proposed Change

Add a `pluginRepositories {}` block to the DSL of `settings.gradle`. The `pluginRepositories` block is parsed in the same phase as the `buildScript` block, before the remaining instructions in the settings file are parsed. A `pluginRepositories` block is only allowed as a top-level element. It introduces new `PluginRepositoriesHandler` and `PluginRepository` interfaces which work similarly to the `RepositoryHandler` and `ArtifactRepository` interfaces.

The `InitialPassStatementTransformer` and `BuildScriptTransformer` classes will be updated to be aware of the special handling needed to deal with the `pluginRepositories` DSL block.

## Test Cases

- `pluginRepositories` block can be read from `settings.gradle`
- `pluginRepositories` block supports defining a `maven` plugin repository
- `pluginRepositories` block is not supported in `ProjectScript`s
- `pluginRepositories` block must come before other blocks in the `settings.gradle` script
- `pluginRepositories` block must be a top-level block (not nested)
- Only one `pluginRepositores` block is allowed in each script

## Code Review

- [x] Does the change work?
    - [x] Try out the feature, executing it like a end-user would.
    - [x] Check corner cases and try to break it in various ways.
    - [x] Are the error messages informative?
- [x] Is the change sufficiently tested?
    - [x] Are there appropriate levels of unit & integration tests?
    - [x] Do the tests indicate what they are actually testing?
    - [x] Are the tests in the right location?
    - [x] Can new tests be consolidated with any existing tests?
- [x] Does it change the public API?
    - [x] Has @Incubating been used appropriately?
    - [x] Does it preserve backward compatibility?
- [ ] Is it sufficiently documented?
    - [ ] Is the user guide documentation in the best location?
    - [ ] Is the user guide documentation clear and informative?
    - [ ] If there should be samples, are they helpful and tested appropriately?
    - [ ] Is there sufficient API/DSL documentation?
    - [ ] Is the API/DSL documentation clear and informative?
    - [ ] Do the release notes clearly convey the value of the feature?
    - [ ] Do the release notes explain the feature and link to more documentation?
- [x] Is it implemented well?
    - [x] Does it minimize surface area (particularly public)?
    - [x] Does it follow our coding conventions? (note that we don't have coding conventions formalized but it's something to keep in mind)
    - [x] Does it use appropriate data structures?
    - [x] Does it minimize potential for invalid states?
    - [x] Does it suitably reuse existing infrastructure?
    - [x] Does it suitably consider concurrency?
    - [x] Does it suitably consider failure modes?
    - [x] Does it suitably consider performance?
    - [x] Does it introduce new types or move existing ones? Are they located in the appropriate package? (e.g. internal classes in internal packages)

**Comment by oehme** [comment]
@DanielThomas You can now try out the new functionality in the examples.

**Comment by eljobe** [comment]
@DanielThomas We've changed our process a little bit. When you are happy with this feature, please just add the "accepted" label to it.

**Comment by eljobe** [comment]
@DanielThomas It would be great if you or someone from your team could try out this functionality in our sample projects and let us know if you are happy with it.

**Comment by DanielThomas** [comment]
@rspieldenner is our on call guy this week, so I'll punt that to him; but I'll take a look by the end of the day if he doesn't get a chance.

**Comment by DanielThomas** [comment]
Sorry we didn't get to this last week. Looking now.
