### ISSUE TITLE
Can add autorization settings to plugin repositories

### ISSUE THREAD

**Issue by oehme** [gradle/stable-plugins-dsl#20]
## Motivation

Users might want to add authentication information to their plugin repository declaration.

## Proposed Change

Once #19 is implemented, this will most likely just work out of the box. Still, it needs to be tested and reviewed.

## Code Review

- [] Does the change work?
    - [] Try out the feature, executing it like a end-user would.
    - [] Check corner cases and try to break it in various ways.
    - [] Are the error messages informative?
- [] Is the change sufficiently tested?
    - [] Are there appropriate levels of unit & integration tests?
    - [] Do the tests indicate what they are actually testing?
    - [] Are the tests in the right location?
    - [] Can new tests be consolidated with any existing tests?
- [] Does it change the public API?
    - [] Has @Incubating been used appropriately?
    - [] Does it preserve backward compatibility?
- [] Is it sufficiently documented?
    - [] Is the user guide documentation in the best location?
    - [] Is the user guide documentation clear and informative?
    - [] If there should be samples, are they helpful and tested appropriately?
    - [] Is there sufficient API/DSL documentation?
    - [] Is the API/DSL documentation clear and informative?
    - [] Do the release notes clearly convey the value of the feature?
    - [] Do the release notes explain the feature and link to more documentation?
- [] Is it implemented well?
    - [] Does it minimize surface area (particularly public)?
    - [] Does it follow our coding conventions? (note that we don't have coding conventions formalized but it's something to keep in mind)
    - [] Does it use appropriate data structures?
    - [] Does it minimize potential for invalid states?
    - [] Does it suitably reuse existing infrastructure?
    - [] Does it suitably consider concurrency?
    - [] Does it suitably consider failure modes?
    - [] Does it suitably consider performance?
    - [] Does it introduce new types or move existing ones? Are they located in the appropriate package? (e.g. internal classes in internal packages)

**Comment by eljobe** [comment]
I am about to get started on this one, but wanted to confirm the scope for this change. Which of the following do we want to implement for each of Maven and Ivy plugin repositories?

Maven
- [ ] all of [AuthenticationSupported](https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/groovy/org/gradle/api/artifacts/repositories/AuthenticationSupported.java)
- [ ] artifactUrls (Urls used for finding artifacts, but not POM files.)

Ivy
- [ ] all of [AuthenticationSupported](https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/groovy/org/gradle/api/artifacts/repositories/AuthenticationSupported.java)
- [ ] ivyPattern (support for finding alternate locations of ivy files.)
- [ ] archivePattern (support for finding alternate locations of artifact files and ivy files.)
- [ ] layout (support for non-standard ivy layouts)

**Comment by oehme** [comment]
I'd say let's only do authentication for now (also change the title of this issue) and wait with the others until someone actually requests them. Authentication seems important enough to do up-front.

**Comment by eljobe** [comment]
Implemented in gradle/gradle@b63c488d002cb3fdf31856fbe7149684454c692a

**Comment by oehme** [comment]
Code looks good and I just tried it out and it works as expected. I added a basic example to the repository, so others can try it out too.

**Comment by eljobe** [comment]
@oehme Did you actually push your example to the repo? I'm not seeing any commits.

**Comment by oehme** [comment]
Indeed, I forgot to push :)
