### ISSUE TITLE
Design Publishing Plugins to Maven/Ivy Repositories

### ISSUE THREAD

**Issue by eljobe** [gradle/stable-plugins-dsl#3]
We need to support publishing Gradle plugins to Maven/Ivy Repositories complete with whatever metadata enables the mapping from plugin id and version to a Maven/Ivy artifact.

**Comment by oehme** [comment]
I started spiking this in the `java-gradle-plugin` plugin.

**Comment by oehme** [comment]
Spike is here: https://github.com/gradle/gradle/commit/e64e161a019beb6becd3b0c342ff2461944d9f1e

Usage gets simplified to this: https://github.com/gradle/stable-plugins-dsl/commit/259839c88742100a0631e9a935360706b0f590da

**Comment by eljobe** [comment]
Well, that's certainly a **lot** easier.
