### ISSUE TITLE
Collect Deep Thoughts on Applying Plugins

### ISSUE THREAD

**Issue by eljobe** [gradle/stable-plugins-dsl#33]
## Motivation

There are lots of proposals floating around for how we might be able to support conveniently applying plugins and configuring their tasks and consuming the APIs they expose across multiple projects in a multi-project build. We need to collect the proposals and evaluate their relative merits in a single place to more clearly understand how we want applying plugins to work for the future of Gradle.
 
## Proposed Change

We will write a document capturing several different possible ways to proceed and invite the larger engineering team to provide feedback on the document to make sure we have all our bases covered.

**Comment by oehme** [comment]
The [design session](https://docs.google.com/document/d/18kMjtZ5xhGmmEIpRSFX3AM1msflz-lu7MKViL83pLAs/) ended with many valuable insights and a clear preference for the current problem:

```
plugins {
  id 'com.foo.bar' version '1.0' noApply()
}

subprojects {
  if(someProperty) {
    apply plugin: 'com.foo.bar'
  }
}
```
