### ISSUE TITLE
Search gradlePluginsPortal for dependencies

### ISSUE THREAD

**Issue by eljobe** [gradle/stable-plugins-dsl#35]
## Problem

When using the `pluginRepositories {}` block, and resolving a plugin from a custom repository which has dependencies on another plugin which is available in the `gradlePluginsPortal` the dependency is not found.

Originally reported in the [Gradle Forum](https://discuss.gradle.org/t/can-plugins-dsl-be-used-with-plugins-that-have-dependencies-on-other-plugins/18134).
## Proposed Change

We need to fix this. One thing we could do is to make the `DefaultGradlePluginPortal` implement `BackedByArtifactRepository` and provide the maven ree
## Code review
- [ ] Does the change work?
- [ ] Is the change sufficiently tested?
- [ ] Does it change the public API?
- [ ] Is it sufficiently documented?
- [ ] Is it implemented well?

**Comment by KyleChamberlin** [comment]
I was curious if there is a workaround for this currently, I am running into this now.

**Comment by oehme** [comment]
@KyleChamberlin Sorry I was sloppy with the board: This issue is already fixed in Gradle 3.0
