### ISSUE TITLE
Design applying plugins in multiple projects at once

### ISSUE THREAD

**Issue by eljobe** [gradle/stable-plugins-dsl#4]
Users need to be able to apply plugins to multiple projects like `allprojects {}` and `subprojects {}` for the previous plugins mechanism.

**Comment by oehme** [comment]
I wrote a first draft of the M2 design spec with use cases and a rough implementation plan that is up for discussion.

**Comment by oehme** [comment]
I adjusted the document to our new plan, please have a look.

**Comment by oehme** [comment]
We've all agreed on the new plan and implemented it on master.
